name = "forcolormap"
description= "A small Fortran colormap library"
version = "0.8.0"
license = "MIT"
author = "Vincent Magnin, AliG"
copyright = "Copyright 2023-2024, Vincent Magnin & AliG"
maintainer = "https://github.com/vmagnin/forcolormap/issues"
homepage   = "https://github.com/vmagnin/forcolormap"
categories = ["graphics"]
keywords   = ["Fortran", "fpm", "colormap"]

[dependencies]
forimage = {git="https://github.com/gha3mi/forimage.git"}

[[example]]
name = "demo"
source-dir = "example"
main = "demo.f90"

[[example]]
name = "demo_reverse"
source-dir = "example"
main = "demo_reverse.f90"

[[example]]
name = "example1"
source-dir = "example"
main = "example1.f90"

[[example]]
name = "info"
source-dir = "example"
main = "info.f90"

[[example]]
name = "extract"
source-dir = "example"
main = "extract.f90"

[build]
auto-executables = true
auto-tests = true
auto-examples = false
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
