name = "forcolormap"
description= "A Fortran colormap library"
version = "0.9.0"
license = "MIT"
author = "Vincent Magnin, Seyed Ali Ghasemi"
copyright = "Copyright 2023-2025, Vincent Magnin & Seyed Ali Ghasemi"
maintainer = "https://github.com/vmagnin/forcolormap/issues"
homepage   = "https://github.com/vmagnin/forcolormap"
categories = ["graphics"]
keywords   = ["Fortran", "colormap", "fpm", "CMake"]

[dependencies]
forimage = {git="https://github.com/gha3mi/forimage.git"}

[[example]]
name = "demo"
source-dir = "example"
main = "demo.f90"

[[example]]
name = "demo_reverse"
source-dir = "example"
main = "demo_reverse.f90"

[[example]]
name = "example1"
source-dir = "example"
main = "example1.f90"

[[example]]
name = "info"
source-dir = "example"
main = "info.f90"

[[example]]
name = "colormaps_list"
source-dir = "example"
main = "colormaps_list.f90"

[[example]]
name = "extract"
source-dir = "example"
main = "extract.f90"

[[example]]
name = "modify"
source-dir = "example"
main = "modify.f90"

[[example]]
name = "create"
source-dir = "example"
main = "create.f90"

[build]
auto-executables = true
auto-tests = true
auto-examples = false
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[extra.ford]
project             = "ForColormap"
year                = "2023-2025"
summary             = 'A Fortran library for colormaps'
project_github      = "https://github.com/vmagnin/forcolormap"
author              = "Vincent Magnin, Seyed Ali Ghasemi"
license             = "MIT"
src_dir             = ["src", "example", "test"]
output_dir          = "doc"
source              = true
incl_src            = true
graph               = true
coloured_edges      = true
search              = true
print_creation_date = true
sort                = "permission-alpha"
display             = ["public", "private", "protected"]
favicon             = "logo/logo_forcolormap-roma_8.svg"

[extra.fortitude.check]
exclude = ["scripts"]
ignore = ["C003", "C121", "S001", "C092", "S061"]