name: Setup Fortran Conda CI/CD

on:
  push:
    branches: [main, ali-dev]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  test_fpm:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    name: ${{ matrix.os }}_${{ matrix.compiler }}_fpm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gfortran, ifx, flang-new, nvfortran]
        include:
          - os: ubuntu-latest
            extra-packages: ""
          - os: windows-latest
            extra-packages: ""
          - os: macos-latest
            extra-packages: ""
        exclude:
          - os: macos-latest
            compiler: flang-new
          - os: macos-latest
            compiler: ifx
          - os: macos-latest
            compiler: nvfortran
          - os: windows-latest
            compiler: nvfortran
  
    steps:
      - name: Setup Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: ${{ matrix.compiler }}
          platform: ${{ matrix.os }}

      - name: fpm test (debug)
        if: always()
        run: fpm test --profile debug --compiler ${{ matrix.compiler }} --verbose

      - name: fpm test (release)
        if: always()
        run: fpm test --profile release --compiler ${{ matrix.compiler }} --verbose

      - name: fpm example (debug)
        if: always()
        run: fpm run --example --all --profile debug --compiler ${{ matrix.compiler }} --verbose

      - name: fpm example (release)
        if: always()
        run: fpm run --example --all --profile release --compiler ${{ matrix.compiler }} --verbose

  doc_ford:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]') }}
    name: Generate FORD Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Generate FORD Documentation
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: gfortran
          platform: ubuntu-latest
          generate-doc-ford: true
          ford-working-directory: .
          ford-config: ford.yml
          ford-output-directory: doc
          ford-branch: gh-pages
          ford-target-folder: .

  test_cmake:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    name: ${{ matrix.os }}_${{ matrix.compiler }}_cmake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gfortran, ifx, flang-new, nvfortran]
        include:
          - os: ubuntu-latest
            extra-packages: ""
          - os: windows-latest
            extra-packages: ""
          - os: macos-latest
            extra-packages: ""
        exclude:
          - os: macos-latest
            compiler: flang-new
          - os: macos-latest
            compiler: ifx
          - os: macos-latest
            compiler: nvfortran
          - os: windows-latest
            compiler: nvfortran
  
    steps:
      - name: Setup Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: ${{ matrix.compiler }}
          platform: ${{ matrix.os }}

      - name: cmake test (debug)
        if: always()
        run: |
          cmake -S . -B build/cmake/debug -DCMAKE_BUILD_TYPE=Debug -G Ninja -DBUILD_TESTING=TRUE
          cmake --build build/cmake/debug --config Debug --verbose
          ctest --test-dir build/cmake/debug --output-on-failure -VV

      - name: cmake test (release)
        if: always()
        run: |
          cmake -S . -B build/cmake/release -DCMAKE_BUILD_TYPE=Release -G Ninja -DBUILD_TESTING=TRUE
          cmake --build build/cmake/release --config Release --verbose
          ctest --test-dir build/cmake/release --output-on-failure -VV
      
      - name: cmake example (debug)
        if: always()
        run: |
          cmake -S . -B build/cmake/debug -DCMAKE_BUILD_TYPE=Debug -G Ninja -DBUILD_FORCOLORMAP_EXAMPLES=true
          cmake --build build/cmake/debug --config Debug --verbose

      - name: cmake example (release)
        if: always()
        run: |
          cmake -S . -B build/cmake/release -DCMAKE_BUILD_TYPE=Release -G Ninja -DBUILD_FORCOLORMAP_EXAMPLES=true
          cmake --build build/cmake/release --config Release --verbose

      - name: cmake install (static)
        if: always()
        run: |
          cmake -S . -B build/cmake/static -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=. -G Ninja
          cmake --build build/cmake/static --config Release
          cmake --install build/cmake/static --config Release --verbose

      - name: cmake install (shared)
        if: always()
        run: |
          cmake -S . -B build/cmake/shared -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=. -G Ninja
          cmake --build build/cmake/shared --config Release
          cmake --install build/cmake/shared --config Release --verbose

  linter_fortitude:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    name: Run Fortitude Linter
    runs-on: ubuntu-latest
    steps:
      - name: Run Fortitude Linter
        uses: gha3mi/setup-fortran-conda@latest
        with:
          fortitude-check: true
          fortitude-settings: "--output-format github"